services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always                       # always restart
    environment:
      MYSQL_DATABASE: 'board'              # name of database
      MYSQL_USER: 'seongha'                # sample is the name of user
      MYSQL_PASSWORD: '1234'          # password for sample user
      MYSQL_ROOT_PASSWORD: '1234'     # password for root user
    ports:
      - '3306:3306'                       # host port 3306 is mapper to docker port 3306
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: